Security fixes
humanmade/crop-thumbnails pull request #2
Opened 2020-09-11 10:06 UTC by datnguyen-sc

## Description

Fix issues highlighted by HM-Minimum coding standards.

2020-09-11 11:24 UTC, Nikschavan requested changes
I think we should revert the indentation/white-space changes (either in this PR or I can do this in a separate one later) so that it is easier to get this merged into the upstream repo.

The plan is to get the security fixes merged to upstream in the near term so that we don't end up maintaining the fork for a few fixes.

2020-09-11 11:24 UTC, Nikschavan commented on functions/backendpreparer.php
> +		featuredImageLinkButton+= '<a class="button cropThumbnailsLink" href="#" data-cropthumbnail=\'{"image_id":'+ parseInt(wp.media.featuredImage.get()) +',"viewmode":"single","posttype":"<?php echo esc
I believe this should be `esc_js()`

```suggestion
		featuredImageLinkButton+= '<a class="button cropThumbnailsLink" href="#" data-cropthumbnail=\'{"image_id":'+ parseInt(wp.media.featuredImage.get()) +',"viewmode":"single","posttype":"<?php echo esc_js( get_post_type() ); ?>"}\' title="<?php esc_attr_e('Crop Featured Image','crop-thumbnails') ?>">';
```

2020-09-11 11:24 UTC, Nikschavan commented on functions/backendpreparer.php
> +					var cropButton = $('<button class="button cropThumbnailsLink" style="margin-top:1em" data-cropthumbnail=\'{"image_id":'+ parseInt(props.featuredImageId) +',"viewmode":"single","posttype":"<?php
Same as above, the change should be `esc_js` I believe.

2020-09-11 11:24 UTC, Nikschavan commented on functions/settingsscreen.php
> +							security: '<?php echo esc_attr( wp_create_nonce( "cpt_quicktest-ajax-nonce" ) );//only for quicktest ?>'
```suggestion
							security: '<?php echo esc_js( wp_create_nonce( "cpt_quicktest-ajax-nonce" ) );//only for quicktest ?>'
```

2020-09-14 07:29 UTC, datnguyen-sc commented
@Nikschavan: Changed `esc_attr` to `esc_js`.  For the spacing, I think it should be alright as all the changes to spacing are to remove unnecessary spaces. I'm not changing spacing character, e.g. space to tab, etc.

2020-09-14 07:31 UTC, Nikschavan approved these changes

2020-09-14 08:55 UTC, merged